default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Google Play Internal"
  lane :internal do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'internal')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store
  end
end
